name: Package
on: [push,pull_request]

env:
  version: ${{github.head_ref}}${{github.ref}}
jobs:
  build-macos:

    runs-on: macos-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build .app
      run: |
        npm run presenter-make
        build/build-macos.sh
        zip -r build/output/BAPSicle.zip build/output/BAPSicle.app
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: BAPSicle-${{ env.version }}-MacOS
        path: |
          build/output/BAPSicle.zip

  build-ubuntu:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build executable
      run: |
        npm run presenter-make
        build/build-linux.sh
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: BAPSicle-${{ env.version }}-Ubuntu
        path: |
          build/output/BAPSicle

  build-windows:

    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build .exe
      run: |
        npm run presenter-make
        build/build-windows.bat no-venv
    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: BAPSicle-${{ env.version }}-Windows
        path: |
          build/output/BAPSicle.exe
          install/
